##########################################################
# 사용자 정의
##########################################################
user:
  error:
    fillInStackTrace: false
    printStackTrace: true

##########################################################
# 스케줄 pool 갯수
##########################################################
scheduler:
  poolSize: 5
##########################################################
# Page 정의
##########################################################
pageing:
  page: 0
  size: 10
  direction: asc
  properties: A,B

mockdir: D:\PRJ\hybird\mock\
tourlistDir: C:\PRJ\project\initData\

